<?php

/**
 * @file
 * Contains bat.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function bat_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bat module.
    case 'help.page.bat':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A generic booking framework for building booking applications') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_toolbar().
 */
function bat_toolbar() {
  $items = [];
  $items['bat'] = array(
    '#type' => 'toolbar_item',
    '#attached' => array(
      'library' => array(
        'bat/drupal.bat.toolbar',
      ),
    ),
  );

  return $items;
}
